
version: '3.0'
services:
  postgres:
    image: postgres:9.6.16
    container_name: tpvpg
    environment:
        TZ: "America/Mexico_City"
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: tpvpos.1235
        POSTGRES_DB: db_tpv
    ports:
        - '45432:5432'
    restart: always
    volumes:
        - /vol_devposgrest_v1/postgres:/var/lib/postgresql/data
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
